-- 1. Retrieve the names of all products and their respective categories
SELECT product_name, category_name
FROM Products
JOIN Categories ON Products.category_id = Categories.category_id;

-- 2. Identify the customer who has placed the order with the highest total value
SELECT Customers.customer_id, Customers.customer_name, MAX(order_total) AS highest_order_value
FROM Orders
JOIN Customers ON Orders.customer_id = Customers.customer_id
GROUP BY Customers.customer_id, Customers.customer_name
ORDER BY highest_order_value DESC
LIMIT 1;

-- 3. Add a new customer to the database
INSERT INTO Customers (customer_name, email, phone, address)
VALUES ('John Doe', 'john.doe@example.com', '123-456-7890', '123 Elm Street');

-- 4. Update the price of a specific product
UPDATE Products
SET price = 19.99
WHERE product_id = 101; -- Replace 101 with the actual product ID

-- 5. Remove a discontinued product from the product listing
DELETE FROM Products
WHERE product_id = 202; -- Replace 202 with the actual product ID

-- 6. Find the average purchase value for each customer
SELECT Customers.customer_id, Customers.customer_name, AVG(Orders.order_total) AS average_purchase_value
FROM Orders
JOIN Customers ON Orders.customer_id = Customers.customer_id
GROUP BY Customers.customer_id, Customers.customer_name;

-- 7. List all orders placed in a specific month
SELECT *
FROM Orders
WHERE EXTRACT(MONTH FROM order_date) = 7; -- Replace 7 with the desired month (1-12)

-- 8. Determine the total revenue generated by each product category
SELECT Categories.category_name, SUM(Products.price * OrderDetails.quantity) AS total_revenue
FROM OrderDetails
JOIN Products ON OrderDetails.product_id = Products.product_id
JOIN Categories ON Products.category_id = Categories.category_id
GROUP BY Categories.category_name;

-- 9. Find the top 10 most popular products based on the quantity sold
SELECT Products.product_name, SUM(OrderDetails.quantity) AS total_quantity_sold
FROM OrderDetails
JOIN Products ON OrderDetails.product_id = Products.product_id
GROUP BY Products.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;

-- 10. Display customer names along with their order IDs
SELECT Customers.customer_name, Orders.order_id
FROM Orders
JOIN Customers ON Orders.customer_id = Customers.customer_id;
